announcements/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/help',        to: 'pages#help'
  get    '/about',       to: 'pages#about'
  get    '/contact',     to: 'pages#contact'
  get    'pages/search', to: 'pages#search'
  get    'pages/get_current_user_announcements', to: 'pages#get_current_user_announcements'
  get    'pages/most_recent', to: 'pages#most_recent'
  get    'pages/most_viewed', to: 'pages#most_viewed'
  get    'pages/best_rated',  to: 'pages#best_rated'

  get    '/signup',      to: 'users#new'

  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  get 'users/new_edit_name', to: 'users#new_edit_name'
  get 'users/new_edit_username', to: 'users#new_edit_username'
  get 'users/new_edit_phone', to: 'users#new_edit_phone'
  get 'users/new_edit_email', to: 'users#new_edit_email'
  get 'users/new_edit_password', to: 'users#new_edit_password'

  patch 'users/edit_name', to: 'users#edit_name'
  patch 'users/edit_username', to: 'users#edit_username'
  patch 'users/edit_phone', to: 'users#edit_phone'
  patch 'users/edit_email', to: 'users#edit_email'
  patch 'users/edit_password', to: 'users#edit_password'

  resources :users

  resource :announcements do
    resource :ratings
    resource :images
  end

  resources :categories do
    resource :announcements
  end

  get '*path', to: 'pages#not_found'

end

announcements/app/views/pages/_recommendation-item.html.erb
<div class="recommendation-item">
  <%= link_to announcements_path(:id => announcement.id)  do %>
      <p>
        <%= announcement.title %>
      </p>
      <% if announcement.images.count > 0 %>
          <p>
            <%= image_tag(announcement.images[0].source_string, width: '200px', height: '150px') %>
          </p>
      <% else %>
          <%= image_tag("/uploads/no-image.jpg", width: '300px', height: '200px') %>
      <% end %>
      <% if announcement.price_value != nil %>
          <p class="recommendation-price">
            <span><%= announcement.price_value %> <%= announcement.price_currency %></span>
          </p>
      <%end %>
  <% end %>
</div>

announcements/app/views/pages/about.html.erb
<div class="page-title"><span>About Page</span></div>

<hr>

announcements/app/views/pages/best-rated-ann.html.erb
<div class="page-title"><span>Best Rated Announcements</span></div>

<hr>

<% if @announcements.count == 0 %>
    <p>No rated announcements</p>
<% else %>
    <% @announcements.each do |announcement| %>
        <%= render partial: 'layouts/announcement-item', locals: { announcement: announcement } %>
    <% end %>
<% end %>

announcements/app/views/pages/contact.html.erb
<div class="page-title"><span>Contact Page</span></div>

<hr>

announcements/app/views/pages/help.html.erb
<div class="page-title"><span>Help Page</span></div>

<hr>

announcements/app/views/pages/home.html.erb
<div class="recommendations">
  <div class="row" id="most-recent">
    <div class="col-md-12">
      <div class="row recommendation-name page-title">
        <div class="col-md-12">
          <span>Most recent</span>
          <hr>
        </div>
      </div>
      <div class="row recommendation-items">
        <% get_most_recent.first(3).each do |announcement| %>
            <div class="col-md-4">
              <%= render partial: 'recommendation-item', locals: { announcement: announcement } %>
            </div>
        <% end %>
      </div>
      <div class="row recommendation-see-all">
        <div class="col-md-12">
          <%= link_to(pages_most_recent_path) do %>
              <span>Check more...</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row" id="most-viewed">
    <div class="col-md-12">
      <div class="row recommendation-name page-title">
        <div class="col-md-12">
          <span>Most viewed</span>
          <hr>
        </div>
      </div>
      <div class="row recommendation-items">
        <% get_most_viewed.first(3).each do |announcement| %>
            <div class="col-md-4">
              <%= render partial: 'recommendation-item', locals: { announcement: announcement } %>
            </div>
        <% end %>
      </div>
      <div class="row recommendation-see-all">
        <div class="col-md-12">
          <%= link_to(pages_most_viewed_path) do %>
              <span>Check more...</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row" id="best-rated">
    <div class="col-md-12">
      <div class="row recommendation-name page-title">
        <div class="col-md-12">
          <span>Best rated</span>
          <hr>
        </div>
      </div>
      <div class="row recommendation-items">
        <% get_best_rated.first(3).each do |announcement| %>
            <div class="col-md-4">
              <%= render partial: 'recommendation-item', locals: { announcement: announcement } %>
            </div>
        <% end %>
      </div>
      <div class="row recommendation-see-all">
        <div class="col-md-12">
          <%= link_to(pages_best_rated_path) do %>
              <span>Check more...</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr>
</div>

announcements/app/views/pages/most-recents-ann.html.erb
<div class="page-title"><span>Most Recent Announcements</span></div>

<hr>

<% if @announcements.count == 0 %>
    <p>No recent announcements</p>
<% else %>
    <% @announcements.each do |announcement| %>
        <%= render partial: 'layouts/announcement-item', locals: { announcement: announcement } %>
    <% end %>
<% end %>

announcements/app/views/pages/most-viewed-ann.html.erb
<div class="page-title"><span>Most Viewed Announcements</span></div>

<hr>

<% if @announcements.count == 0 %>
    <p>No viewed announcements</p>
<% else %>
    <% @announcements.each do |announcement| %>
        <%= render partial: 'layouts/announcement-item', locals: { announcement: announcement } %>
    <% end %>
<% end %>

announcements/app/views/pages/not_found.html.erb
<div class="page-title"><span>Page Not Found: 404</span></div>

announcements/app/views/pages/search-result.html.erb
<div class="page-title"><span>Search results</span></div>

<hr>

<% if @announcements.count == 0 %>
    <p>No result found for your searching criteria</p>
<% else %>
    <% @announcements.each do |announcement| %>
        <%= render partial: 'layouts/announcement-item', locals: { announcement: announcement } %>
    <% end %>
<% end %>

announcements/app/views/pages/user-announcements.html.erb
<div class="page-title"><span>My Announcements</span></div>

<hr>

<% if @announcements.count == 0 %>
    <p>You have no announcements added</p>
    <button type="button" class="btn btn-default" >
      <%= link_to 'Add new announcement', new_announcements_path %>
    </button>
<% else %>
    <button type="button" class="btn btn-default" >
      <%= link_to 'Add new announcement', new_announcements_path %>
    </button>
    <% @announcements.each do |announcement| %>
        <%= render partial: 'layouts/announcement-item', locals: { announcement: announcement } %>
    <% end %>
<% end %>