announcements/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/help',        to: 'pages#help'
  get    '/about',       to: 'pages#about'
  get    '/contact',     to: 'pages#contact'
  get    'pages/search', to: 'pages#search'
  get    'pages/get_current_user_announcements', to: 'pages#get_current_user_announcements'
  get    'pages/most_recent', to: 'pages#most_recent'
  get    'pages/most_viewed', to: 'pages#most_viewed'
  get    'pages/best_rated',  to: 'pages#best_rated'

  get    '/signup',      to: 'users#new'

  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  get 'users/new_edit_name', to: 'users#new_edit_name'
  get 'users/new_edit_username', to: 'users#new_edit_username'
  get 'users/new_edit_phone', to: 'users#new_edit_phone'
  get 'users/new_edit_email', to: 'users#new_edit_email'
  get 'users/new_edit_password', to: 'users#new_edit_password'

  patch 'users/edit_name', to: 'users#edit_name'
  patch 'users/edit_username', to: 'users#edit_username'
  patch 'users/edit_phone', to: 'users#edit_phone'
  patch 'users/edit_email', to: 'users#edit_email'
  patch 'users/edit_password', to: 'users#edit_password'

  resources :users

  resource :announcements do
    resource :ratings
    resource :images
  end

  resources :categories do
    resource :announcements
  end

  get '*path', to: 'pages#not_found'

end

announcements/app/views/layouts/_announcement-item.html.erb
<div class="announcement-item">
  <%= link_to announcements_path(:id => announcement.id)  do %>
      <div class="row">
        <div class="col-md-8">
          <div class="row title">
            <div class="col-md-12">
              <p>
                <%= announcement.title %>
              </p>
            </div>
          </div>
          <div class="row description">
            <div class="col-md-12">
              <p>
                <%= simple_format announcement.description %>
              </p>
            </div>
          </div>
          <div id="gradient"></div>
          <div class="row price">
            <div class="col-md-12">
              <% if announcement.price_value != nil %>
                  <p>
                    <span><%= announcement.price_value %> <%= announcement.price_currency %></span>
                  </p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <% if announcement.images.count > 0 %>
              <p>
                <%= image_tag(announcement.images[0].source_string, width: '200px', height: '150px') %>
              </p>
          <% else %>
              <%= image_tag("/uploads/no-image.jpg", width: '300px', height: '200px') %>
          <% end %>
        </div>
      </div>
  <% end %>
  <hr>
</div>

announcements/app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</footer>

announcements/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Announcements", root_path, class:"navbar-brand" %>
    </div>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if logged_in? %>

            <% if current_user.role == "user" %>
                <li><%= link_to "My announcements", pages_get_current_user_announcements_path %></li>
            <% end %>

            <% if current_user.role == "admin" %>
                <li><%= link_to "Users", users_path %></li>
            <% end %>

            <% if current_user.role == "admin" %>
                <li><%= link_to "Categories", categories_path %></li>
            <% end %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

announcements/app/views/layouts/_search-bar.html.erb
<div class="input-group">
  <%= form_tag(pages_search_path, method: 'get') do %>
      <div class="input-group-btn  search-keyword">
        <%= text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: 'Search term...' %>
      </div>
      <div class="input-group-btn search-category">
        <%= select_tag :category, options_for_select(['Announcements'] + get_all_categories.map { |category| category.name }), {class: 'form-control'}%>
      </div>
      <div class="input-group-btn">
        <%= button_tag(type: 'submit', class: "btn btn-default") do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </div>
  <% end %>
</div>

announcements/app/views/layouts/_side-menu.html.erb
<div class="side-menu">
  <nav class="navbar navbar-default" role="navigation">
    <div class="side-menu-container">
      <ul class="nav navbar-nav">
        <% get_all_categories.each do |category| %>
            <%= link_to_in_li category.name, category_path(category)%>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

announcements/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Announcements</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="header">
  <%= render 'layouts/header' %>
</div>
<div class="content">
  <div class="container">
    <div class="row sub-header shadow">
      <div class="col-md-2">
        <div class="add-announcement">
          <button type="button" class="btn btn-default" >
            <%= link_to 'Add announcement', new_announcements_path %>
          </button>
        </div>
      </div>
      <div class="col-md-10">
        <div class="search-bar">
          <%= render 'layouts/search-bar' %>
        </div>
      </div>
    </div>
    <div class="row content-min-height shadow">
      <div class="col-md-2">
        <%= render 'layouts/side-menu' %>
      </div>
      <div class="col-md-10">
        <p class="success"><%= flash[:success] %></p>
        <p class="error"><%= flash[:danger] %></p>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<div class="footer">
  <%= render 'layouts/footer' %>
</div>
</body>
</html>