announcements/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get    '/help',        to: 'pages#help'
  get    '/about',       to: 'pages#about'
  get    '/contact',     to: 'pages#contact'
  get    'pages/search', to: 'pages#search'
  get    'pages/get_current_user_announcements', to: 'pages#get_current_user_announcements'
  get    'pages/most_recent', to: 'pages#most_recent'
  get    'pages/most_viewed', to: 'pages#most_viewed'
  get    'pages/best_rated',  to: 'pages#best_rated'

  get    '/signup',      to: 'users#new'

  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  get 'users/new_edit_name', to: 'users#new_edit_name'
  get 'users/new_edit_username', to: 'users#new_edit_username'
  get 'users/new_edit_phone', to: 'users#new_edit_phone'
  get 'users/new_edit_email', to: 'users#new_edit_email'
  get 'users/new_edit_password', to: 'users#new_edit_password'

  patch 'users/edit_name', to: 'users#edit_name'
  patch 'users/edit_username', to: 'users#edit_username'
  patch 'users/edit_phone', to: 'users#edit_phone'
  patch 'users/edit_email', to: 'users#edit_email'
  patch 'users/edit_password', to: 'users#edit_password'

  resources :users

  resource :announcements do
    resource :ratings
    resource :images
  end

  resources :categories do
    resource :announcements
  end

  get '*path', to: 'pages#not_found'

end

announcements/app/models/user.rb
class User < ApplicationRecord
  has_many :announcements, dependent: :destroy
  enum roles: { admin: "admin", user: "user" }
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50, minimum: 3 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255, minimum: 5 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
end

announcements/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new user_params

    if params[:from] == 'user_list'
      if @user.save
        flash[:success] = "User #{@user.username} successfully added!"
        redirect_to users_path
      else
        render 'new'
      end
    else
      if @user.save
        log_in @user
        flash[:success] = 'Welcome to the Announcements!'
        redirect_to root_path
      else
        render 'new'
      end
    end
  end

  def update
    @user = User.find params[:id]

    if @user.update user_params
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy

    if params[:to] == 'home_page'
      redirect_to root_path
    else
      redirect_to users_path
    end

  end

  def new_edit_name
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render :edit_name }
    end
  end

  def new_edit_username
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render :edit_username }
    end
  end

  def new_edit_phone
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render :edit_phone }
    end
  end

  def new_edit_email
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render :edit_email }
    end
  end

  def new_edit_password
    @user = User.find(params[:id])

    respond_to do |format|
      format.js { render :edit_password }
    end
  end

  def edit_name
    @user = User.find params[:id]

    edit_param @user, 'Your firsname and lastname successfully updated!', 'Error updating your firsname and lastname!'
  end

  def edit_username
    @user = User.find params[:id]

    edit_param @user, 'Your username successfully updated!', 'Error updating your username!'
  end

  def edit_phone
    @user = User.find params[:id]

    edit_param @user, 'Your phone successfully updated!', 'Error updating your phone!'
  end

  def edit_email
    @user = User.find params[:id]

    if @user.authenticate(user_params[:password])
      edit_param @user, 'Your email successfully updated!', 'Error updating your email!'
    else
      edit_param_error @user, 'Invalid password!'
    end
  end

  def edit_password
    @user = User.find params[:id]

    if @user.authenticate(edit_password_param_check)
      if params[:user][:password] == params[:user][:password_confirmation]
        if params[:user][:old_password] != params[:user][:password]
          edit_param @user, 'Your password successfully updated!', 'Error updating your password!'
        else
          edit_param_error @user, 'Old and new passwords have to be different!'
        end
      else
        edit_param_error @user, 'Different password confirmation from new password!'
      end
    else
      edit_param_error @user, 'Invalid password!'
    end
  end

  def delete_my_account
    byebug
    @user = User.find params[:id]
    @user.destroy

    redirect_to root_path
  end

  private

  def user_params
    form_params = {}
    if logged_in? && current_user.role == User.roles[:admin]
      form_params = params.require(:user).permit(:username, :email, :firstname, :lastname, :phone, :password, :password_confirmation, :role)
    else
      form_params = params.require(:user).permit(:username, :email, :firstname, :lastname, :phone, :password, :password_confirmation)
      form_params["role"] = "user"
    end
    form_params
  end

  def edit_password_param_check
    form_params = {}

    form_params["password"] = params[:user][:old_password]
  end

 def edit_param user, success_message, error_message
    if user.update(user_params)
      flash[:success] = success_message
    else
      flash[:danger] = error_message
    end
    redirect_to user
  end

  def edit_param_error user, error_message
    flash[:danger] = error_message
    redirect_to user
  end
end

announcements/app/helpers/users_helper.rb
module UsersHelper
end

announcements/app/views/users/_edit-email-form.html.erb
<%= form_for(@user, :url => users_edit_email_path(id: @user.id)) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            you to edit your profile name:
          </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, 'New email' %><br/>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %><br/>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <%= f.submit "Save", class: "btn btn-default" %>
<% end %>
<%= link_to current_user do%>
    <button class="btn btn-default">Cancel</button>
<% end %>

announcements/app/views/users/_edit-name-form.html.erb
<%= form_for(@user, :url => users_edit_name_path(id: @user.id)) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            you to edit your profile name:
          </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :firstname,'New firstname' %><br/>
      <%= f.text_field :firstname, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :lastname, 'New lastname' %><br/>
      <%= f.text_field :lastname, class: "form-control" %>
    </div>

    <%= f.submit "Save", class: "btn btn-default" %>
<% end %>
<%= link_to current_user do%>
    <button class="btn btn-default">Cancel</button>
<% end %>

announcements/app/views/users/_edit-phone-form.html.erb
<%= form_for(@user, :url => users_edit_phone_path(id: @user.id)) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            you to edit your profile name:
          </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :phone, 'New phone' %><br/>
      <%= f.text_field :phone, class: "form-control" %>
    </div>

    <%= f.submit "Save", class: "btn btn-default" %>
<% end %>
<%= link_to current_user do%>
    <button class="btn btn-default">Cancel</button>
<% end %>

announcements/app/views/users/_edit-username-form.html.erb
<%= form_for(@user, :url => users_edit_username_path(id: @user.id)) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            you to edit your profile name:
          </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :username, 'New username' %><br/>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <%= f.submit "Save", class: "btn btn-default" %>
<% end %>
<%= link_to current_user do%>
    <button class="btn btn-default">Cancel</button>
<% end %>

announcements/app/views/users/_form.html.erb
<%= form_for(@user, url: {action: 'create', :from => 'user_list'}) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <p>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            you to sign up:
          </p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :username %><br/>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email %><br/>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %><br/>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Confirm password" %><br/>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <% if logged_in? && current_user.role == "admin" %>
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, User.roles { |r| r }, {}, class: "form-control" %>
        </div>
    <% end %>

    <%= f.submit "Create my account", class: "btn btn-default" %>
<% end %>

announcements/app/views/users/edit.html.erb
<div class="page-title"><span>Edit user</span></div>

<hr>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

announcements/app/views/users/edit_email.js.erb
$("#edit-email-form").html("<%=escape_javascript(render :partial=>'edit-email-form')%>");

announcements/app/views/users/edit_name.js.erb
$("#edit-name-form").html("<%=escape_javascript(render :partial=>'edit-name-form')%>");

announcements/app/views/users/edit_password.js.erb
$("#edit-password-form").html("<%=escape_javascript(render :partial=>'edit-password-form')%>");

announcements/app/views/users/edit_phone.js.erb
$("#edit-phone-form").html("<%=escape_javascript(render :partial=>'edit-phone-form')%>");

announcements/app/views/users/edit_username.js.erb
$("#edit-username-form").html("<%=escape_javascript(render :partial=>'edit-username-form')%>");

announcements/app/views/users/index.html.erb
<div class="page-title"><span>User list</span></div>

<hr>

<% @users.each do |user| %>
    <div class="row">
      <div class="col-md-3">
        <p><%= user.username %></p>
      </div>
      <div class="col-md-3">
        <p><%= user.email %></p>
      </div>
      <div class="col-md-3">
        <p><%= user.role %></p>
      </div>
      <div class="col-md-1">
        <%= link_to 'Show', user_path(user) %>
      </div>
      <div class="col-md-2">
        <% if user.username != 'admin' %>
            <%= link_to 'Delete user', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
            <br>
        <% end %>
      </div>
    </div>
    <hr>
<% end %>

<%= link_to new_user_path do %>
    <button class="btn btn-default">Add new user</button>
<% end %>

announcements/app/views/users/new.html.erb
<div class="page-title"><span>Sign up</span></div>

<hr>

<div class="col-md-4">
  <%= render 'form' %>
</div>

announcements/app/views/users/show.html.erb
<div class="page-title"><span>My account settings</span></div>

<hr>

<div class="row">
  <div class="col-md-2">
    <p><strong>Name</strong></p>
  </div>
  <div class="col-md-8">
    <p><span><%= @user.firstname %> <%= @user.lastname %></span></p>
    <div id="edit-name-form"></div>
  </div>
  <div class="col-md-2">
    <% if current_user.username == @user.username %>
        <p><%= link_to 'Edit', users_new_edit_name_path(id: @user.id), :remote=>true , id: 'edit-name' %></p>
    <% else %>
        <br>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2">
    <p><strong>Username</strong></p>
  </div>
  <div class="col-md-8">
    <p><%= @user.username %></p>
    <div id="edit-username-form"></div>
  </div>
  <div class="col-md-2">
    <% if current_user.username == @user.username %>
        <p><%= link_to 'Edit', users_new_edit_username_path(id: @user.id), :remote=>true , id: 'edit-username' %></p>
    <% else %>
        <br>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2">
    <p><strong>Email</strong></p>
  </div>
  <div class="col-md-8">
    <p><%= @user.email %></p>
    <div id="edit-email-form"></div>
  </div>
  <div class="col-md-2">
    <% if current_user.username == @user.username %>
        <p><%= link_to 'Edit', users_new_edit_email_path(id: @user.id), :remote=>true , id: 'edit-email' %></p>
    <% else %>
        <br>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2">
    <p><strong>Telephone</strong></p>
  </div>
  <div class="col-md-8">
    <p><%= @user.phone %></p>
    <div id="edit-phone-form"></div>
  </div>
  <div class="col-md-2">
    <% if current_user.username == @user.username %>
        <p><%= link_to 'Edit', users_new_edit_phone_path(id: @user.id), :remote=>true , id: 'edit-phone' %></p>
    <% else %>
        <br>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2">
    <p><strong>Password</strong></p>
  </div>
  <div class="col-md-8">
    <br>
    <div id="edit-password-form"></div>
  </div>
  <div class="col-md-2">
    <% if current_user.username == @user.username %>
        <p><%= link_to 'Edit', users_new_edit_password_path(id: @user.id), :remote=>true , id: 'edit-password' %></p>
    <% else %>
        <br>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-2">
    <% if current_user.username == @user.username  and current_user.username != 'admin' %>
        <p><%= link_to 'Delete account', user_path(@user, to: 'home_page'), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% else %>
        <br>
    <% end %>
  </div>
  <div class="col-md-8">
    <br>
  </div>
  <div class="col-md-2">
    <br>
  </div>
</div>